# SPDX-FileCopyrightText: 2022, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

name: Verify schema and script compatibility

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Verify data files against schema
        run: ./verify_schema.sh

      - name: Try generating report
        run: make
